---
title: "Second Homework"
author: "Lavrentiy"
date: "April 2, 2017"
output: html_document
---

Подгружаем необходимые библиотеки и понеслось:
```{r setup, include=FALSE}
library(DESeq2)
library(ggplot2)
library(pheatmap)
library(amap)
library(dbscan)
options(width=120)
knitr::opts_chunk$set(echo = TRUE)
```

##Задание 1

И так сейчас попытка сделать хоть какую-то кластерихацию:
```{r load files, echo=FALSE, warning=FALSE}
counts <- read.csv("GSE89225_Illumina_counts.csv", row.names=1)

conditions <- read.csv("conditions.csv", row.names=1)

mart <- read.table("human_mart.txt", sep="\t", header=1, check.names = F)

```


После этого вырезаем только *8000* самых экспрессированных генов
```{r}
dds <- DESeqDataSetFromMatrix(countData = counts,
                              colData = conditions,
                              design = ~ tissue+cells)
sort_genes<-sort(rowSums(counts(dds)),decreasing = T)[1:8000]
dds <- dds[names(sort_genes), ]
log_dds<-rlog(dds)

cor_matrix <- cor(x = assay(log_dds), y = assay(log_dds))
uncor_matrix <- 1-cor_matrix
```

И делаем кластеризацию

```{r cluster,echo=F,warning=F}
d<-dist(uncor_matrix,method = "euclidean")
## Метод ближайшего соседа в R
hc_single <- hclust(d, method = "single")
plot(hc_single)
## Метод отдаленного соседа в R
hc_compl <- hclust(d, method = "complete")
plot(hc_compl)
## Метод невзвешенного попарного среднего в R UPGMA
hc_avg <- hclust(d, method = "average")
plot(hc_avg)
```

##Задание 2
Теперь взяли датасет без оутлайнера, как в предыдущей домашке
```{r second task, echo=FALSE, warning=FALSE}
counts <- read.csv("GSE89225_Illumina_counts.csv", row.names=1)
counts <- counts[,names(counts) != "treg_NBP_patient3"]
conditions <- read.csv("conditions.csv", row.names=1)
conditions<- conditions[row.names(conditions) != "treg_NBP_patient3", ]#выкидываем оутлайнер
mart <- read.table("human_mart.txt", sep="\t", header=1, check.names = F)

```

И делаем метод k-means для описания паттернов экспрессии  
```{r k-mears clustarisation, echo=FALSE, warning=FALSE}
dds <- DESeqDataSetFromMatrix(countData = counts,
                              colData = conditions,
                              design = ~ tissue+cells)
sort_genes<-sort(rowSums(counts(dds)),decreasing = T)[1:8000]
dds <- dds[names(sort_genes), ]
log_dds<-rlog(dds)
rld<-assay(log_dds)

clustering <- Kmeans(rld, 6, method="correlation", iter.max=200)
head(clustering$cluster)
```
И пытаемся построить Heatmap
```{r heatmap,echo=F,warning=F}
  sort<-sort(clustering$cluster)

sort_colum<-order(conditions$cells,conditions$tissue)
to_visualise <- rld[names(sort), sort_colum]
to_visualise <- t(apply(to_visualise, 1, function(r) {
  (r - min(r)) / (max(r) - min(r))
}))
mat<-as.data.frame(sort)
mat$sort<-factor(mat$sort)
pheatmap(to_visualise, 
         show_rownames =F, cluster_rows = F,
         cluster_cols=F,
         annotation_col = conditions,annotation_row = mat)
```


```{r dbscan,echo=F,warning=F}
library(dbscan)
library(ggplot2)
karta<-read.csv("projection.csv")
ggplot(karta,aes(x = TSNE.1,y = TSNE.2))+geom_point()
res<-dbscan(as.matrix(karta[,2:3]),eps = 4, minPts = 5)
ggplot(karta,aes(x = TSNE.1,y = TSNE.2))+geom_point(aes(color=factor(res$cluster)))
```
